const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const Scan = require('../models/Scan');
const PDFDocument = require('pdfkit');

// Generate PDF report for a scan
router.get('/:id', auth, async (req, res) => {
  try {
    const scan = await Scan.findById(req.params.id);
    if (!scan || scan.user.toString() !== req.user.id) {
      return res.status(404).json({ message: 'Scan not found' });
    }

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=WAST-Report-${scan._id}.pdf`);
    doc.pipe(res);

    // Title
    doc.fontSize(28).fillColor('#00f0ff').text('W.A.S.T. Security Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#999999').text('Web Application Security Testing Platform', { align: 'center' });
    doc.moveDown(1);

    // Horizontal line
    doc.strokeColor('#333333').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(1);

    // Scan Details
    doc.fontSize(14).fillColor('#ffffff').text('Scan Details');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#cccccc');
    doc.text(`Target: ${scan.targetUrl}`);
    doc.text(`Status: ${scan.status}`);
    doc.text(`Risk Level: ${scan.riskLevel}`);
    doc.text(`Scanned: ${new Date(scan.createdAt).toLocaleString()}`);
    doc.text(`Completed: ${scan.completedAt ? new Date(scan.completedAt).toLocaleString() : 'N/A'}`);
    doc.text(`Vulnerabilities Found: ${scan.vulnerabilities?.length || 0}`);
    doc.moveDown(1);

    // Horizontal line
    doc.strokeColor('#333333').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(1);

    // Vulnerabilities
    doc.fontSize(14).fillColor('#ffffff').text('Vulnerabilities');
    doc.moveDown(0.5);

    if (scan.vulnerabilities && scan.vulnerabilities.length > 0) {
      scan.vulnerabilities.forEach((vuln, index) => {
        // Severity color
        let sevColor = '#00f0ff';
        if (vuln.severity === 'Critical') sevColor = '#ff003c';
        else if (vuln.severity === 'High') sevColor = '#ff4d00';
        else if (vuln.severity === 'Medium') sevColor = '#fcee0a';

        doc.fontSize(12).fillColor(sevColor).text(`${index + 1}. [${vuln.severity}] ${vuln.type}`);
        doc.fontSize(9).fillColor('#cccccc');
        doc.text(`   URL: ${vuln.url}`);
        doc.text(`   Description: ${vuln.description}`);
        if (vuln.evidence) doc.text(`   Evidence: ${vuln.evidence}`);
        if (vuln.suggestion) {
          doc.fillColor('#00ff41').text(`   Fix: ${vuln.suggestion}`);
        }
        doc.moveDown(0.5);
      });
    } else {
      doc.fontSize(10).fillColor('#00ff41').text('No vulnerabilities detected. Target appears secure.');
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#666666').text('Generated by W.A.S.T. Platform', { align: 'center' });

    doc.end();

  } catch (err) {
    console.error('PDF Generation Error:', err);
    res.status(500).json({ message: 'Failed to generate PDF' });
  }
});

module.exports = router;
